-- AlterTable
ALTER TABLE "Setting"
ADD COLUMN "pointsPerGHC" DECIMAL(10,2) NOT NULL DEFAULT 1.00,
ADD COLUMN "ghcPerPoint" DECIMAL(10,2) NOT NULL DEFAULT 0.10,
ADD COLUMN "minimumPointsToRedeem" INTEGER NOT NULL DEFAULT 100;
